version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3001:3000
    depends_on:
      - prometheus
